{{- if .Values.agent.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "genui-playground.fullname" . }}-agent
  labels:
    {{- include "genui-playground.agent.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.agent.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "genui-playground.agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "genui-playground.agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "genui-playground.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: agent
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "genui-playground.agent.image" . }}
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.agent.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /copilotkit
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /copilotkit
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: PORT
              value: {{ .Values.agent.service.targetPort | quote }}
            {{- if .Values.agent.env }}
            {{- toYaml .Values.agent.env | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
      {{- with .Values.agent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}