{{- if .Values.agent.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "genui-playground.fullname" . }}-agent
  labels:
    {{- include "genui-playground.agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.agent.service.type }}
  ports:
    - port: {{ .Values.agent.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "genui-playground.agent.selectorLabels" . | nindent 4 }}
{{- end }}