{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "genui-playground.fullname" . }}-secrets
  labels:
    {{- include "genui-playground.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.secrets.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}